version: 0.1

env:
  shell: /bin/bash
  parameter-store:
    SECRET: /2020wa15340
    
phases:
  build:
    commands:
      - echo "Deploying application into the server."
    finally:
      - echo setup has completed successfully.


